version: "3.8"
services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./mongo/.env
    container_name: mongodb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on: 
      - mongodb
    container_name: backend

volumes:
  mongodbdata: